networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  percona:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  neo4j:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  rethinkdb:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  aerospike:
    driver: ${VOLUMES_DRIVER}
  caddy:
    driver: ${VOLUMES_DRIVER}
  meilisearch:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}
  mosquitto:
    driver: ${VOLUMES_DRIVER}
  confluence:
    driver: ${VOLUMES_DRIVER}
  sonarqube:
    driver: ${VOLUMES_DRIVER}
  cassandra:
    driver: ${VOLUMES_DRIVER}
  graylog:
    driver: ${VOLUMES_DRIVER}
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}
  react:
    driver: ${VOLUMES_DRIVER}
    
x-args-template: &args-template
 #args:
  - CHANGE_SOURCE=${CHANGE_SOURCE}
  - BASE_IMAGE_TAG_PREFIX=${PHP_FPM_BASE_IMAGE_TAG_PREFIX}
  - LARADOCK_PHP_VERSION=${PHP_VERSION}
  - LARADOCK_PHALCON_VERSION=${PHALCON_VERSION}
  - INSTALL_BZ2=${PHP_FPM_INSTALL_BZ2}
  - INSTALL_ENCHANT=${PHP_FPM_INSTALL_ENCHANT}
  - INSTALL_GMP=${PHP_FPM_INSTALL_GMP}
  - INSTALL_GNUPG=${PHP_FPM_INSTALL_GNUPG}
  - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
  - XDEBUG_PORT=${PHP_FPM_XDEBUG_PORT}
  - INSTALL_PCOV=${PHP_FPM_INSTALL_PCOV}
  - INSTALL_PHPDBG=${PHP_FPM_INSTALL_PHPDBG}
  - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
  - INSTALL_SSH2=${PHP_FPM_INSTALL_SSH2}
  - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
  - INSTALL_XSL=${PHP_FPM_INSTALL_XSL}
  - INSTALL_SMB=${PHP_FPM_INSTALL_SMB}
  - INSTALL_IMAP=${PHP_FPM_INSTALL_IMAP}
  - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
  - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
  - INSTALL_CASSANDRA=${PHP_FPM_INSTALL_CASSANDRA}
  - INSTALL_ZMQ=${PHP_FPM_INSTALL_ZMQ}
  - INSTALL_GEARMAN=${PHP_FPM_INSTALL_GEARMAN}
  - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
  - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
  - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
  - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
  - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
  - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
  - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
  - INSTALL_OCI8=${PHP_FPM_INSTALL_OCI8}
  - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
  - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
  - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
  - PG_CLIENT_VERSION=${POSTGRES_CLIENT_VERSION}
  - INSTALL_POSTGIS=${PHP_FPM_INSTALL_POSTGIS}
  - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
  - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
  - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
  - INSTALL_PHALCON=${PHP_FPM_INSTALL_PHALCON}
  - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
  - INSTALL_TAINT=${PHP_FPM_INSTALL_TAINT}
  - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
  - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
  - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
  - INSTALL_XLSWRITER=${PHP_FPM_INSTALL_XLSWRITER}
  - INSTALL_FAKETIME=${PHP_FPM_INSTALL_FAKETIME}
  - INSTALL_IONCUBE=${PHP_FPM_INSTALL_IONCUBE}
  - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
  - INSTALL_CACHETOOL=${PHP_FPM_INSTALL_CACHETOOL}
  - INSTALL_YAML=${PHP_FPM_INSTALL_YAML}
  - INSTALL_RDKAFKA=${PHP_FPM_INSTALL_RDKAFKA}
  - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
  - INSTALL_ADDITIONAL_LOCALES=${PHP_FPM_INSTALL_ADDITIONAL_LOCALES}
  - INSTALL_MYSQL_CLIENT=${PHP_FPM_INSTALL_MYSQL_CLIENT}
  - INSTALL_PING=${PHP_FPM_INSTALL_PING}
  - INSTALL_SSHPASS=${PHP_FPM_INSTALL_SSHPASS}
  - INSTALL_MAILPARSE=${PHP_FPM_INSTALL_MAILPARSE}
  - INSTALL_PCNTL=${PHP_FPM_INSTALL_PCNTL}
  - ADDITIONAL_LOCALES=${PHP_FPM_ADDITIONAL_LOCALES}
  - INSTALL_FFMPEG=${PHP_FPM_FFMPEG}
  - INSTALL_AUDIOWAVEFORM=${PHP_FPM_AUDIOWAVEFORM}
  - INSTALL_WKHTMLTOPDF=${PHP_FPM_INSTALL_WKHTMLTOPDF}
  - WKHTMLTOPDF_VERSION=${PHP_FPM_WKHTMLTOPDF_VERSION}
  - INSTALL_XHPROF=${PHP_FPM_INSTALL_XHPROF}
  - INSTALL_XMLRPC=${PHP_FPM_INSTALL_XMLRPC}
  - INSTALL_PHPDECIMAL=${PHP_FPM_INSTALL_PHPDECIMAL}
  - INSTALL_ZOOKEEPER=${PHP_FPM_INSTALL_ZOOKEEPER}
  - INSTALL_SSDB=${PHP_FPM_INSTALL_SSDB}
  - INSTALL_TRADER=${PHP_FPM_INSTALL_TRADER}
  - INSTALL_EVENT=${PHP_FPM_INSTALL_EVENT}
  - LEGACY_OPENSSL=${PHP_LEGACY_OPENSSL}
  - DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL=${PHP_DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL}
  - DOWNGRADE_OPENSSL_TLS_VERSION=${PHP_DOWNGRADE_OPENSSL_TLS_VERSION}
  - PUID=${PHP_FPM_PUID}
  - PGID=${PHP_FPM_PGID}
  - IMAGEMAGICK_VERSION=${PHP_FPM_IMAGEMAGICK_VERSION}
  - LOCALE=${PHP_FPM_DEFAULT_LOCALE}
  - NEW_RELIC=${PHP_FPM_NEW_RELIC}
  - NEW_RELIC_KEY=${PHP_FPM_NEW_RELIC_KEY}
  - NEW_RELIC_APP_NAME=${PHP_FPM_NEW_RELIC_APP_NAME}
  - INSTALL_DOCKER_CLIENT=${PHP_FPM_INSTALL_DOCKER_CLIENT}
  - INSTALL_DNSUTILS=${PHP_FPM_INSTALL_DNSUTILS}
  - INSTALL_POPPLER_UTILS=${PHP_FPM_INSTALL_POPPLER_UTILS}
  - http_proxy
  - https_proxy
  - no_proxy
  - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
  - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
  - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
  - APACHE_INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}
  - APACHE_FOR_MAC_M1=${APACHE_FOR_MAC_M1}
  - TZ=${ALL_IN_ONE_TIMEZONE}
  - ALL_IN_ONE_DATA_PATH=${ALL_IN_ONE_DATA_PATH}
  - ALL_IN_ONE_DATA_APPLICATON_PATH=${ALL_IN_ONE_DATA_APPLICATON_PATH}
  - APACHE_HOST_LOG_PATH=${ALL_IN_ONE_APACHE_HOST_LOG_PATH}
  - APACHE_SITES_PATH=${ALL_IN_ONE_APACHE_SITES_PATH}
  - APACHE_SSL_PATH=${ALL_IN_ONE_APACHE_SSL_PATH}

x-build-template: &build-template
    context: ../
    dockerfile: ./laradock-sr/all-in-one/Dockerfile
    args: *args-template
  
x-sr-template: &sr-template
  build :
    << : *build-template
  #volumes:
    #- ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    #- ${APACHE_HOST_LOG_PATH}:/var/log/apache2
    #- ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    #- ${APACHE_SSL_PATH}:/etc/apache2/ssl
  ports:
    - "${APACHE_HOST_HTTP_PORT}:80"
    - "${APACHE_HOST_HTTPS_PORT}:443"
  expose:
    - "9000"
  extra_hosts:
    - "dockerhost:${DOCKER_HOST_IP}"
  environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    - DOCKER_HOST=tcp://${DOCKER_HOST_IP}:2376
    - DOCKER_TLS_VERIFY=1
    - DOCKER_TLS_CERTDIR=/certs
    - DOCKER_CERT_PATH=/certs/client
    - FAKETIME=${PHP_FPM_FAKETIME}
    #depends_on:
    #- workspace
  networks:
    - frontend
    - backend
    #links:
    #- docker-in-docker

  
services:

### All-In-One Utilities ##################################
    sr:
      << : *sr-template
      
    sr-platform:
      << : *sr-template
      
    sr-report:
      << : *sr-template
        
    sr-app:
      << : *sr-template
      
    sr-admin:
      <<: *sr-template
      
    sr-without-admin:
      <<: *sr-template
    
